REPLACE INTO VincitaPremio VALUES
('Oscar', 'Al miglior film', 2010, 32, NULL, NULL),
('Oscar', 'Al miglior film', 2011, 58, NULL, NULL),
('Oscar', 'Al miglior film', 2012, 40, NULL, NULL),
('Oscar', 'Al miglior film', 2013, 25, NULL, NULL),
('Oscar', 'Al miglior film', 2014, 18, NULL, NULL),
('Oscar', 'Al miglior film', 2015, 16, NULL, NULL),
('Oscar', 'Al miglior film', 2016, 24, NULL, NULL),
('Oscar', 'Al miglior film', 2017, 62, NULL, NULL),
('Oscar', 'Al miglior film', 2018, 34, NULL, NULL),
('Oscar', 'Al miglior film', 2019, 1, NULL, NULL),
('Oscar', 'Al miglior attore', 2010, 81, 'Lorenzo', 'Fiore'),
('Oscar', 'Al miglior attore', 2011, 9, 'Luca', 'Fiore'),
('Oscar', 'Al miglior attore', 2012, 67, 'Gabriele', 'Fabbricatore'),
('Oscar', 'Al miglior attore', 2013, 52, 'Alessio', 'Gallo'),
('Oscar', 'Al miglior attore', 2014, 69, 'Pasquale', 'Fabbricatore'),
('Oscar', 'Al miglior attore', 2015, 19, 'Sara', 'Della Valle'),
('Oscar', 'Al miglior attore', 2016, 19, 'Diego', 'Scognamiglio'),
('Oscar', 'Al miglior attore', 2017, 77, 'Alessio', 'Zannelli'),
('Oscar', 'Al miglior attore', 2018, 36, 'Vincenzino', 'Esposito'),
('Oscar', 'Al miglior attore', 2019, 10, 'Sara', 'Scognamiglio'),
('Oscar', 'Al miglior attore non protagonista', 2010, 60, 'Sara', 'Scognamiglio'),
('Oscar', 'Al miglior attore non protagonista', 2011, 91, 'Loris', 'Zannelli'),
('Oscar', 'Al miglior attore non protagonista', 2012, 59, 'Alessio', 'Fabbricatore'),
('Oscar', 'Al miglior attore non protagonista', 2013, 99, 'Giada', 'Della Valle'),
('Oscar', 'Al miglior attore non protagonista', 2014, 58, 'Diego', 'Scognamiglio'),
('Oscar', 'Al miglior attore non protagonista', 2015, 15, 'Antonio', 'Scognamiglio'),
('Oscar', 'Al miglior attore non protagonista', 2016, 90, 'Carmen', 'Zannelli'),
('Oscar', 'Al miglior attore non protagonista', 2017, 88, 'Pasquale', 'Fabbricatore'),
('Oscar', 'Al miglior attore non protagonista', 2018, 93, 'Guido', 'Fabbricatore'),
('Oscar', 'Al miglior attore non protagonista', 2019, 45, 'Lorenza', 'Fiore'),
('Oscar', 'Al miglior regista', 2010, 50, 'Giulio', 'Fabbricatore'),
('Oscar', 'Al miglior regista', 2011, 72, 'Sara', 'Scognamiglio'),
('Oscar', 'Al miglior regista', 2012, 48, 'Sara', 'Scognamiglio'),
('Oscar', 'Al miglior regista', 2013, 94, 'Sara', 'Scognamiglio'),
('Oscar', 'Al miglior regista', 2014, 31, 'Tom', 'Fabbricatore'),
('Oscar', 'Al miglior regista', 2015, 84, 'Alessio', 'Zannelli'),
('Oscar', 'Al miglior regista', 2016, 37, 'Lorenzo', 'Zannelli'),
('Oscar', 'Al miglior regista', 2017, 76, 'Alessio', 'Zannelli'),
('Oscar', 'Al miglior regista', 2018, 30, 'Gianmarco', 'Fabbricatore'),
('Oscar', 'Al miglior regista', 2019, 43, 'Carmen', 'Zannelli'),
('Oscar', 'Al miglior film in lingua straniera', 2010, 96, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2011, 89, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2012, 69, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2013, 63, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2014, 27, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2015, 9, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2016, 79, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2017, 56, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2018, 10, NULL, NULL),
('Oscar', 'Al miglior film in lingua straniera', 2019, 67, NULL, NULL);
